[package]
name = "rust-pip"
version = "0.0.1"
edition = "2021"
description = "WORK IN PROGRESS: Pip rewritten in Rust"
authors = ["Jan Bronicki janbronicki@gmail.com"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/John15321/rust-pip"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.58", features = ["backtrace"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
structopt = { version = "0.3.26", features = ["color"] }
strum = "0.24.1"
strum_macros = "0.24.2"


[dev-dependencies]
